### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by FezVrasta** [jacobharasimo/angular-popper#1]
Hi, I'd like to know the status of this project.
When ready I'd like to link it within the README of the official repository.

Thanks!

**Comment by jacobharasimo** [comment]
I have put it aside for a bit. I think I can look at it come October

**Comment by FezVrasta** [comment]
I see, such a shame! Please ping me here if the library reaches a stable state.

If you need any improvements to the core library in order to make this one work open an issue and I'll review it.

**Comment by jacobharasimo** [comment]
Just to many projects right now, i will focus on it shortly as it was very
close to done before

**Comment by FezVrasta** [comment]
Hi, any updates?

We are near the v1 release of Popper.js and we have a library for React, Vue.js (soon for Ember.js), we just need one for Angular 😇

**Comment by jacobharasimo** [comment]
I did some progress awhile ago. Maybe I can find time this holiday season
to finish it up. It's been a busy time, 90% of the code is there so anyone
can of course contribute

**Comment by FezVrasta** [comment]
Hi, just an heads up, we reached beta.3 right now, if no bug raises in the next week, I'm going to promote this beta.3 to RC and move out of beta officially.

It would be great to release it with already integrations with Angular 🔥

**Comment by jacobharasimo** [comment]
check the current state i think its ok as pushed some code recently.

**Comment by jacobharasimo** [comment]
Federico you can maybe contact me privately and we can discuss?
